name: Run Postman API Tests

on:
  push:
    branches:
      - Dev
  pull_request:
    branches:
      - master

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Postman Collection via CLI
        run: npx postman-cli collection run "48432856"
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
